version: "3.9"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: cookbook-flaskpocket-pocketbase
    restart: unless-stopped
    ports:
      - "${POCKETBASE_PORT}:8090"
    volumes:
      - cookbook-flaskpocket-pocketbase:/pb_data
  web:
    build: '.'
    ports:
      - '${FLASK_PORT}:5000'
    volumes:
      - ./:/srv

volumes:
  cookbook-flaskpocket-pocketbase:
